import { ArrowRight, Check, Gem, HelpCircle, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { useSkillSwap } from "@/contexts/SkillSwapContext";

export default function Wallet() {
  const [, navigate] = useLocation();
  const { state, purchase, markWalletVisited } = useSkillSwap();
  const [education, setEducation] = useState(!state.walletVisited);
  useEffect(() => { markWalletVisited(); }, [markWalletVisited]);
  return <div className="wallet-page"><section className="wallet-hero"><div><p className="page-kicker"><Gem size={14} /> Skill Wallet</p><h1>Keep your learning <em>moving.</em></h1><p>Points make learning value easy to understand: teach to earn, learn to spend, and only top up when you choose.</p></div><div className="wallet-amount"><span>Available balance</span><strong>{state.wallet}</strong><b>Skill Points</b>{state.starterPoints > 0 ? <small>Includes {state.starterPoints} Starter Reward points</small> : null}</div></section><section className="wallet-flow"><span>Teach</span><ArrowRight size={15} /><span>Earn Points</span><ArrowRight size={15} /><span>Learn</span><ArrowRight size={15} /><span>Grow</span></section><section className="wallet-content"><article className="transaction-card"><div className="section-line"><div><p className="page-kicker">Transaction history</p><h2>Every movement is clear.</h2></div><span>{state.transactions.length} recorded</span></div>{state.transactions.length ? <div className="transaction-list">{state.transactions.map((transaction) => <div key={transaction.id}><span className={transaction.amount > 0 ? "transaction-icon positive" : "transaction-icon"}>{transaction.amount > 0 ? "+" : "−"}</span><div><strong>{transaction.type}</strong><small>{new Date(transaction.date).toLocaleDateString()} · {transaction.status}</small></div><b className={transaction.amount > 0 ? "positive" : ""}>{transaction.amount > 0 ? "+" : ""}{transaction.amount} pts</b><span className="balance-after">{transaction.balance} balance</span></div>)}</div> : <div className="wallet-empty"><Sparkles size={26} /><h3>Your starter reward is waiting.</h3><button className="primary-action" onClick={() => navigate("/welcome")}>Activate 20 free points</button></div>}</article><aside className="wallet-buy"><p className="page-kicker">Optional top-up</p><h3>Need a little more momentum?</h3><p>You do not need to buy points to begin. Starter points are designed to help you experience the platform first.</p><div>{[10, 25, 50].map((points) => <button key={points} onClick={() => purchase(points)}><span>{points} points</span><b>Demo top-up</b></button>)}</div></aside></section>{education ? <div className="points-education" role="dialog"><HelpCircle size={23} /><p className="page-kicker">What are Skill Points?</p><h2>Use points to learn from teachers, book consultations, and reward helpful learning.</h2><ul><li>Teach a useful skill to earn more.</li><li>Book learning sessions and consultations.</li><li>Starter points do not expire in this demo.</li></ul><button className="primary-action" onClick={() => setEducation(false)}>Start using points <Check size={16} /></button></div> : null}</div>;
}
